# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://songhaojie.com
date_format: "ordinal"
title: 我的日志
subtitle: "时间折叠"
description: "Gerald的个人博客"
keywords: Gerald
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Gerald Song
organization: 
organization_url: 
github_username: geraldsong
location: Shenzhen, China
email: haojie1009@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/

## Gem
gems: [jekyll-paginate,jekyll-geo-pattern,rouge,kramdown]
plugins_dir:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
 

collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: geraldsong/geraldsong.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
#comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
#    username: 
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: mzlogin
#    repo: blog-comments
#    oauth:
#        client_id: d2e1cbbd298958076462
#        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
#gitalk:
#    owner: mzlogin
#    repo: blog-comments
#    clientID: d2e1cbbd298958076462
#    clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# 在使用其它评论组件时可点击显示 Disqus
#lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
#simple_jekyll_search:
    # 是否支持全文搜索
#    fulltext: false
    # 最多显示多少条搜索结果
#    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-80669434-1
